etianen/django-python3-ldap

- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
I was trying to use this package, but the LDAP server that I needed to connect to requires TLS. 
This pull request adds a setting to enable initiating TLS after connection.
> Add basic TLS support

- setup.py
Old package 'python3_ldap' is now called 'ldap3'. And 'python3_ldap' version 0.9.5.3 is no more available on pypi
> Fix dependencies with new package ldap3

- django_python3_ldap/__init__.py
- setup.py
It appears that the ldap3 project removes older revisions from pypi as
new ones are released, eventually breaking the == version.
This will allow the current version to be pulled.
> Changed ldap3 dependency version to >=

- CHANGELOG.rst
- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
Prior to this, it was assumed that anonymous queries were allowed to get users when using ```python manage.py ldap_sync_users``` but now I have added the options to be set inside settings.py as follows for those who do not let anonymous queries to work
```python
LDAP_AUTH_CONNECTION_USERNAME = None
LDAP_AUTH_CONNECTION_PASSWORD = None
```
> Added settings for non-anonymous user syncing to be allowed

- .gitignore
- .travis.yml
- django_python3_ldap/conf.py
- django_python3_ldap/tests.py
- django_python3_ldap/utils.py
- setup.py
- tox.ini
* fix the few code incompatibilities with six
* add tox to test locally with various python versions
Fix for #23 
tox is callable with :
```sh
LDAP_AUTH_URL=ldap://localhost LDAP_AUTH_SEARCH_BASE=dc=example,dc=com
LDAP_AUTH_TEST_USER_USERNAME=test_user
LDAP_AUTH_TEST_USER_PASSWORD=test_password tox
```
> Python2.7 compatibility

- django_python3_ldap/utils.py
This also makes the example about appending a custom filter (which correctly includes encapsulating parentheses) to actually work.
> LDAP filters are always encapsulated in parentheses

- django_python3_ldap/ldap.py
- django_python3_ldap/management/commands/ldap_sync_users.py
Replace NoArgsCommand as it is deprecated as of Django 1.10.
```
./manage.py ldap_sync_users
/home/robbie/work/nmap_tool/venv/lib/python3.4/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprec
ated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
RemovedInDjango110Warning
```
I took the directly from a commit made to your watson repository.. :-)
> Fixing Django 1.10 warnings and enable ldap attributes for iter_users

- django_python3_ldap/__init__.py
- django_python3_ldap/ldap.py
- django_python3_ldap/tests.py
- tox.ini
...for Active Directory due to missing attributes if a valid user but invalid group was specified. Added test procedures for Django 1.9 and 1.10 with Python 2.7 and 3.4.
> Fixed issue where a non-existent group with an existent user would cause a KeyError

- setup.py
django-python3-ldap crashes with 2.x
> ldap3 2.x is incompatible, setting 1.4.0 limit

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
If the LDAP server is down or unreachable for any reason, the entire Django app will hang. This adds the ability to set a timeout in `ldap3`, to prevent that from happenning
> Add timeouts kwargs on Server/Connection construction

- django_python3_ldap/utils.py
This allows using : in LDAP attribute names, so I could have a custom format search filter like memberOf:1.2.840.113556.1.4.1941: which will recursively search groups in Active Directory.
It also allows using \* for matches like mail=*@example.com.
> Allow ':' and '*' in LDAP values

- README.rst
- django_python3_ldap/ldap.py
- django_python3_ldap/tests.py
- django_python3_ldap/utils.py
This allows a further query to be done in sync_user_relations() as per issue #207 
The signature of the sync_user_relations() changes to `custom_sync_user_relations(user, ldap_attributes, ldap_connection)`
A sample that performs an additional query to pull all the groups/nested groups and adds them into django user database, would look like the below:-
```python
"""LDAP group expansion code"""
import ldap3
from django.contrib.auth.models import Group
from .settings import LDAP_AUTH_SEARCH_BASE
def custom_sync_user_relations(user, ldap_attributes, ldap_connection):
dn = ldap_connection.response[0].get("dn")
if ldap_connection.search(
search_base=LDAP_AUTH_SEARCH_BASE,
search_filter=f"(member:1.2.840.113556.1.4.1941:={dn})",
search_scope=ldap3.SUBTREE,
dereference_aliases=ldap3.DEREF_NEVER, …
```
> Pass connection object to LDAP_AUTH_SYNC_USER_RELATIONS

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/management/commands/ldap_sync_users.py
- django_python3_ldap/tests.py
- django_python3_ldap/utils.py
- tests/django_python3_ldap_test/settings.py
Hello! This is a proposed addition which resolves #199. An optional positional argument is added to the `ldap_sync_users` management command, which allows the caller to provide a list of lookups to sync individual users if desired. As described in the issue, this essentially "chunks" the lookups based on the _n_ fields in `LDAP_AUTH_USER_LOOKUP_FIELDS`. Two tests are also added to cover this new behavior.
> Allow syncing individual users with ldap_sync_users management command

- django_python3_ldap/utils.py
As force_text is now removed with Django 4, force_str should be used instead, see [here](https://docs.djangoproject.com/en/4.0/releases/4.0/).
> Update for Django 4

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
- tests/django_python3_ldap_test/settings.py
Make use of LDAP3's ServerPool to enable authentication against more than 1 LDAP server.
> use serverpool to enable multiple auth servers

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
Python 3.10 has upped its security protocols, removing `SSLv3` by default. `ldap3` and the underlying OpenSSL libraries still try to fall back on this version as a default, which leads to an `SSLV3_ALERT_HANDSHAKE_FAILURE`.
This patch allows a new setting, `LDAP_AUTH_TLS_VERSION`, which allows specifying a TLS version available in the standard `ssl` library. It connects to LDAP using a `Tls` object from `ldap3` rather than the `start_tls()` function, allowing us to specify the version we need.
Thanks for the amazing package, @etianen - we have been keen users of it for years!
> Allows overriding the SSL/TLS version. (fixes `SSLV3_ALERT_HANDSHAKE_FAILURE` in Python 3.10)

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
This fixes #245 - my apologies for the faulty PR.
This appeared to be working because I had a Django model backend prioritized before the LDAP backend, which was causing the code to appear to work after receiving errors for quite some time, when in fact, the error was no longer triggered but the login was still being handled by the model backend.
> Bug fix: TLS object must go on the server, not connection.

- django_python3_ldap/ldap.py
We were comparing settings.LDAP_AUTH_CONNECTION_USERNAME(not formatted) to the formatted username resulting in an extra rebind every single time even if settings.LDAP_AUTH_CONNECTION_USERNAME
is same as the username passed in kwargs.
This commit fixes that by formatting the username before comparing them
> fix(extra-rebind): format username before compression

- setup.py
`pyasn1` has recently released versions 0.5.x -> https://pypi.org/project/pyasn1/#history.
This change allows for use of the recent versions as well. I noticed that this limitation was added before those versions even existed.
Tests are passing, also no apparent functional regression is observed.
> Support for pyasn1 0.5.x

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
- django_python3_ldap/tests.py
Currently the pool is initiated so that servers are retried indefinetely. This makes it hard to define concrete hard timeout for login operation.
This change exposes ldap3's ServerPool active parameter as setting. That way it provides means to resolve situations as with #264.
Based on the following docs: https://ldap3.readthedocs.io/en/latest/server.html#server-pool
> Expose ldap pool active parameter to limit retries

- README.rst
- django_python3_ldap/conf.py
- django_python3_ldap/ldap.py
I'm running an LDAP server with a handful of old/legacy settings required, which causes this to fail to connect. Pullrequest adds support for entering those settings, and support for other unnamed options through keyword arguments.
> Add additional Tls/SSL arguments
